---
sudo: required

language: ruby

services:
  - docker

before_script:
  - bundle exec kitchen list

script:
  - bundle exec kitchen verify

after_script:
  - bundle exec kitchen list

notifications:
  email:
    on_success: never
    on_failure: always
