- name: Add ksplice apt key
  apt_key:
    url: https://www.ksplice.com/apt/ksplice-archive.asc
    id: 5DE2D4F255E23055D3C40F2CF7CA6265B6D4038E
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Add ksplice apt repository
  apt_repository: repo="deb {{ ksplice_repo_prefix }}/apt/ {{ ansible_distribution_release }} ksplice"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  
- name: Install uptrack package
  apt: name=uptrack state=present

- name: Install confg file
  ini_file:
    dest: /etc/uptrack/uptrack.conf
    section: Auth
    option: accesskey
    value: "{{ ksplice_key }}"

- name: Remove packaged cron job
  file: path=/etc/cron.d/uptrack state=absent

- name: Install cron job
  cron:
    name: uptack
    user: root
    special_time: hourly
    job: export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin && [ -x /usr/sbin/uptrack-upgrade ] && /usr/sbin/uptrack-upgrade --cron
