- name: Add ksplice apt key
  apt_key:
    url: https://www.ksplice.com/apt/ksplice-archive.asc
    id: 5DE2D4F255E23055D3C40F2CF7CA6265B6D4038E
  when: ansible_os_family == 'Debian'

- name: Add ksplice apt repository
  apt_repository: repo="deb {{ ksplice_repo_prefix }}/apt/ {{ ansible_distribution_release }} ksplice"
  when: ansible_os_family == 'Debian'

- name: Add ksplice rpm key
  rpm_key: key=https://ksplice.com/yum/RPM-GPG-KEY-ksplice
  when: ansible_os_family == 'RedHat'

- name: Add ksplice yum repository
  yum_repository:
    name: ksplice-uptrack
    description: Ksplice Uptrack
    baseurl: "{{ ksplice_repo_prefix }}/yum/uptrack/{{ ansible_distribution | lower | replace ('redhat', 'rhel') | replace ('oraclelinux', 'ol') }}/$releasever/$basearch/"
    gpgcheck: yes
    gpgkey: https://www.ksplice.com/yum/RPM-GPG-KEY-ksplice
  when: ansible_os_family == 'RedHat'

- name: Install uptrack package
  package: name=uptrack state=present

- name: Install confg file
  ini_file:
    dest: /etc/uptrack/uptrack.conf
    section: Auth
    option: accesskey
    value: "{{ ksplice_key }}"

- name: Remove packaged cron job
  file: path=/etc/cron.d/uptrack state=absent

- name: Install cron job
  cron:
    name: uptrack
    user: root
    special_time: hourly
    job: export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin && [ -x /usr/sbin/uptrack-upgrade ] && /usr/sbin/uptrack-upgrade --cron
